// This file is generated by Slice Machine. Update with care!

import Faq from './Faq';
import HeroSection from './HeroSection';
import ReviewSection from './ReviewSection';
import Separator from './Separator';

export {
	Faq,
	HeroSection,
	ReviewSection,
	Separator,
};

export const components = {
	faq: Faq,
	hero_section: HeroSection,
	review_section: ReviewSection,
	separator: Separator,
};
