// This file is generated by Slice Machine. Update with care!

import ContactSection from './ContactSection';
import Faq from './Faq';
import Heading from './Heading';
import HeroSection from './HeroSection';
import List from './List';
import ProjectsSection from './ProjectsSection';
import ReviewSection from './ReviewSection';
import Separator from './Separator';
import Services from './Services';
import TechSection from './TechSection';

export {
	ContactSection,
	Faq,
	Heading,
	HeroSection,
	List,
	ProjectsSection,
	ReviewSection,
	Separator,
	Services,
	TechSection,
};

export const components = {
	contact_section: ContactSection,
	faq: Faq,
	heading: Heading,
	hero_section: HeroSection,
	list: List,
	projects_section: ProjectsSection,
	review_section: ReviewSection,
	separator: Separator,
	services: Services,
	tech_section: TechSection,
};
