// This file is generated by Slice Machine. Update with care!

import CardList from './CardList';
import ContactSection from './ContactSection';
import Faq from './Faq';
import Heading from './Heading';
import HeroSection from './HeroSection';
import List from './List';
import Logos from './Logos';
import PageBanner from './PageBanner';
import PriceGuide from './PriceGuide';
import ProjectsSection from './ProjectsSection';
import QuoteBox from './QuoteBox';
import ReviewSection from './ReviewSection';
import Separator from './Separator';
import Services from './Services';
import TechSection from './TechSection';
import Text from './Text';

export {
	CardList,
	ContactSection,
	Faq,
	Heading,
	HeroSection,
	List,
	Logos,
	PageBanner,
	PriceGuide,
	ProjectsSection,
	QuoteBox,
	ReviewSection,
	Separator,
	Services,
	TechSection,
	Text,
};

export const components = {
	card_list: CardList,
	contact_section: ContactSection,
	faq: Faq,
	heading: Heading,
	hero_section: HeroSection,
	list: List,
	logos: Logos,
	page_banner: PageBanner,
	price_guide: PriceGuide,
	projects_section: ProjectsSection,
	quote_box: QuoteBox,
	review_section: ReviewSection,
	separator: Separator,
	services: Services,
	tech_section: TechSection,
	text: Text,
};
